(function () {
  if (localStorage.getItem('allin-disclaimer-v1')) return;

  const banner = document.createElement('div');
  banner.id = 'disclaimerBanner';
  banner.innerHTML = `
    <div style="
      position:fixed;bottom:0;left:0;right:0;z-index:9999;
      background:oklch(0.12 0.02 250/0.97);
      border-top:1px solid oklch(0.34 0.02 250);
      backdrop-filter:blur(8px);
      padding:20px 24px;
      display:flex;align-items:center;gap:20px;flex-wrap:wrap;
      font-family:'Inter',sans-serif;
      box-shadow:0 -8px 32px oklch(0 0 0/0.4);
    " id="disclaimerInner">
      <div style="flex:1;min-width:260px">
        <div style="font-size:13px;font-weight:700;color:#fff;margin-bottom:4px;">
          ⚠️ Informational Use Only — Not Financial Advice
        </div>
        <div style="font-size:12px;color:oklch(0.70 0.01 250);line-height:1.5;">
          Allin Signal provides market opinions generated by a quantitative model. Nothing here is investment advice.
          Signals do not account for fundamentals, news, or your personal situation.
          Past performance does not guarantee future results.
          You are solely responsible for your investment decisions.
          <a href="disclaimer.html" style="color:oklch(0.78 0.14 220);white-space:nowrap">Read full disclaimer →</a>
        </div>
      </div>
      <button id="disclaimerAccept" style="
        flex:none;padding:10px 22px;border-radius:8px;
        background:oklch(0.80 0.17 150);color:oklch(0.12 0.02 250);
        font-size:13px;font-weight:700;border:0;cursor:pointer;white-space:nowrap;
      ">I understand, continue</button>
    </div>`;

  document.body.appendChild(banner);

  document.getElementById('disclaimerAccept').addEventListener('click', () => {
    localStorage.setItem('allin-disclaimer-v1', '1');
    banner.remove();
  });
})();
